<?php
$title = 'Editar Tipo Vehiculo';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<hr>
<?php
$form = $this->form;
$form->setAttribute('action', 
    $this->url('tipovehiculo', array('action' => 'edit', 'id'=>$id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idTipoVehiculo')) ;?>
<div class="form-inline">
    <div class="form-group"> 
    <?php echo $this->formRow($form->get('descripcion')); ?></div>
    <div class="form-group" style="margin-top:1.5%"> <?php echo $this->formInput($form->get('submit')); ?></div>
    <?php echo $this->form()->closeTag($form); ?>

</div>
