<style>
    thead th {   background-color: #5d8b3d; color: white; font-size: 12px}
</style>
<?php
$title = 'Tipos de Vehiculos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('tipovehiculo', array(
    'action' => 'add'));
?>"  class="btn btn-primary">Agregar Tipo Vehiculo</a></p>

<table class="table">
    <thead>
        <tr>
            <th>Id Tipo Veh&iacute;culo</th>
            <th>Descripcion</th>
            <th>&nbsp;</th>
        </tr>
        </head>
    <tbody>
<?php foreach ($tiposdevehiculos as $vehiculo) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($vehiculo->idTipoVehiculo); ?></td>
                <td><?php echo $this->escapeHtml($vehiculo->descripcion); ?></td>
                <td>
                    <a href="<?php echo $this->url('tipovehiculo', array('action' => 'edit', 'id' => $vehiculo->idTipoVehiculo));
    ?>" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a href="<?php echo $this->url('tipovehiculo', array('action' => 'delete', 'id' => $vehiculo->idTipoVehiculo));
    ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
<?php endforeach; ?>
    </tbody></table>
