<?php
if (!$this->zfcUserIdentity()) {
    echo $this->zfcUserLoginWidget();
} else {
echo $this->doctype();
    ?>

    <html lang="en">
        <head>
            <meta charset="utf-8">
            <?php echo $this->headTitle('SIWEST ' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

            <?php
            echo $this->headMeta()
                    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ?>

            <!-- Le styles -->
            <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'img/icono.png', 'href' => $this->basePath() . '/img/icono.png'))
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->prependStylesheet($this->basePath() . '/css/datepicker3.css')
            ?>

            <!-- Scripts -->
            <?php
            echo $this->headScript()
                    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                    ->prependFile($this->basePath() . '/js/jquery.min.js')
                    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                    ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                    ->prependFile($this->basePath() . '/js/boostrap-modal.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            //  ->prependFile($this->basePath() . '/js/picnet.table.filter.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ;
            ?>
            <script type="text/javascript" src="<?php echo $this->basePath() ?>/js/picnet.table.filter.min.js"></script>   
            <script type="text/javascript" src="<?php echo $this->basePath() ?>/js/bootstrap-tab.js"></script>   
            <script type="text/javascript" src="<?php echo $this->basePath() ?>/js/bootstrap-datepicker.js"></script>   
        </head>
        <body>
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" >
                <div class="container">
                    <div class="navbar-header" >
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                  <a class="navbar-brand" style='padding: 0%; margin: 0%' href="<?php echo $this->url('zfcuser', array('action' => 'index')) ?>"><img src="<?php echo $this->basePath('img/caminera1.png') ?>" alt="Sistema Web de Registro de Sanciones de Tránsito" />&nbsp;<?php echo $this->translate('') ?></a>
                    </div>

                    <div class="collapse navbar-collapse" style="margin-top: 1%"><!--style="margin-top: 3%"-->
                        <ul class="nav navbar-nav" >
                            <li class=""><a href="<?php echo $this->url('contravencion', array('action' => 'buscador')) ?>"><?php echo $this->translate('Contravención') ?></a></li>
                            <li class=""><a href="<?php echo $this->url('pago', array('action' => 'index')) ?>"><?php echo $this->translate('Pago de Multa') ?></a></li>
                            <li class=""><a href="<?php echo $this->url('multasdescripcion', array('action' => 'index')) ?>"><?php echo $this->translate('Articulos') ?></a></li>
                                                        <li class=""><a href="<?php echo $this->url('reporte', array('action' => 'multasxrango')) ?>"><?php echo $this->translate('Reporte') ?></a></li>
                            <li ><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Cerrar Sesión') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </nav>
            <div class="container"  > <!--style="margin-top: 10%"-->
                <?php echo $this->content; ?>
                <hr>
                <footer>
                    <p>&copy; <?php echo date('Y') ?>  SIWEST  <?php echo $this->translate('Todos los Derechos Reservados.') ?></p>
                </footer>
            </div> <!-- /container -->
            <?php echo $this->inlineScript() ?>
        </body>
    </html>
<?php } ?>