<style>
    thead th {   background-color: #5d8b3d; color: white; font-size: 12px}
</style>
<?php
$title = 'Registrar Articulo descripción';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<hr>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('multasdescripcion', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idMulta'));
?>
<div class="form-inline">
    <div class="form-group"> 
        <?php echo $this->formRow($form->get('articuloNro')); ?></div>
    <div class="form-group"> <?php echo $this->formRow($form->get('descripcion')); ?></div>
    <div class="form-group"> <?php echo $this->formRow($form->get('jornales')); ?></div>
    <div class="form-group"> <?php echo $this->formRow($form->get('monto')); ?></div>
    <div class="form-group" style="margin-top:1.5%"> <?php echo $this->formInput($form->get('submit')); ?></div>
</div>
<?php echo $this->form()->closeTag($form); ?>

