<?php
$title = 'Eliminar Registro de Multas';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Esta seguro que desea borrar 
  '<?php echo $this->escapeHtml($multasdescripcion->descripcion); ?>'
  '<?php echo $this->escapeHtml($multasdescripcion->articuloNro); ?>'
  
</p>
<?php 
$url = $this->url('multasdescripcion', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$multasdescripcion->idMulta; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
