
<table>
    <tr>
        <td style="padding:5%; padding-top: 0%"><img src="http://'<?php echo $_SERVER['HTTP_HOST']. $this->basePath() ?> '/img/paraguay1.png'" align="left" /></td>
        <td><span style="font-size: 20px; font-weight: bold">MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES</span><br>
            <span>Direccion de Control y Seguridad de Transito</span><br>
            <b>POLICIA CAMINERA</b><br>
            <span><b>Telefono:</b> 532-689 - 584256</span><br>
        </td>
        <td align="right" style="padding:3%"><b>NRO BOLETA:</b><br> 123456</td>
    </tr>  
</table>';
<h3 align="center"> BOLETA DE CONTRAVENCION</h3><br>';
<b>Conductor: </b><?php echo $datosCiudadano->nombre ?><b>C.I: </b><?php echo $datosCiudadano->cedula ?> <b>Nro Registro: </b><?php echo $datosCiudadano->registroNro ?> <b>Municipio:</b><?php echo $mostrarmulta->idMunicipio ?> ;
<b>Vehiculo: </b><?php echo $mostrarmulta->idTipoVehiculo ?> <b>Chapa Nro: </b> <?php echo $mostrarmulta->numeroChapa ?><b>Contravencion: </b><?php echo $mostrarmulta->idMulta ?> <b>km:</b> <?php echo $mostrarmulta->km ?> <b>Ruta:</b> '.$mostrarmulta->ruta. ' <b>Fecha-Hora: </b> '.$mostrarmulta->fecha;
<p><b>Queda Ud. notificado que dentro de los 5 días habiles deberá presentarse a la policia caminera de: '.$mostrarmulta->idMunicipio.' bajo apercibimiento or lo dispuesto en el Articulo 208
    del decreto Ley Nro: 22094 Reglamento general de Tránsito Caminero</b>.</p>';

<span align="right"><b>Fecha:</b><?php $mostrarmulta->fecha ?></span><br>
<span style="font-size:20px"><b>Válido por Cinco (5) días hábiles<b></span>

