<?php 
$title = 'Contravencion';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('contravencion', array( 
        'action'=>'add'));?>">Registrar Contravencion</a></p>

<table class="table">
<tr>
    <th>Nro. Boleta</th>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Cedula</th>
    <th>Direccion</th>
    <th>Telefono</th>
    <th>registroNro</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($ciudadanos as $ciudadano) : ?>
<tr>
    <td><?php echo $this->escapeHtml($ciudadano->idConductor);?></td>
    <td><?php echo $this->escapeHtml($ciudadano->nombre);?></td>
    <td><?php echo $this->escapeHtml($ciudadano->apellido);?></td>
    <td><?php echo $this->escapeHtml($ciudadano->cedula);?></td>
    <td><?php echo $this->escapeHtml($ciudadano->direccion);?></td>
    <td><?php echo $this->escapeHtml($ciudadano->telefono);?></td>
    <td><?php echo $this->escapeHtml($ciudadano->registroNro);?></td>
    <td>
        <a href="<?php echo $this->url('ciudadano',
            array('action'=>'edit', 'id' =>$ciudadano->idConductor));?>">Edit</a>
        <a href="<?php echo $this->url('ciudadano',
            array('action'=>'delete', 'id' =>$ciudadano->idConductor));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
