
<h3 align="center" class="titulo"><?php echo sprintf($this->translate('Cambiar contrase&ntilde;a de %s'), $this->zfcUserDisplayName()); ?></h3><br>
    <?php if ($status === true) : ?>
        <div class="alert alert-success"><?php echo $this->translate('La contrase&ntilde;a ha sido cambiada exitosamente!.'); ?></div>
    <?php elseif ($status === false) : ?>
        <div class="alert alert-error"><?php echo $this->translate('No se pudo cambiar la contrase&ntilde;a. Intenta de nuevo'); ?></div>
    <?php endif; ?>
    <?php
    $form = $this->changePasswordForm;

    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/changepassword'));
    $form->setAttribute('method', 'post');

    $emailElement = $form->get('identity');
    $emailElement->setValue($this->zfcUserIdentity()->getEmail());
    echo $this->form()->openTag($form);
    ?>

    <div class="col-xs-4"></div>
    <div class="col-xs-4">
        <?php echo $this->formElementErrors($form->get('identity')); ?>
        <?php echo $this->formInput($form->get('identity')); ?>


        <?php echo $this->formLabel($form->get('credential')); ?>
        <?php echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential')); ?>

        <?php echo $this->formLabel($form->get('newCredential')); ?>
        <?php echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential')); ?>          

        <?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
        <?php
        echo $this->formInput($form->get('newCredentialVerify'));
        echo $this->formElementErrors($form->get('newCredentialVerify'));
        ?>

        <div style="padding: 3%; float: right">
            <?php echo $this->formInput($form->get('submit')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div style="clear: both"></div>