<style>
    .btn-success{
        background-color: green
    }

</style>
<h3 align="center" class="titulo"><?php echo $this->translate('Hola '); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3><br>
<center>

    <a href="<?php echo $this->url('zfcuser/changepassword') ?>" style="margin: 4%" class="btn btn-primary col-md-2"> Cambiar mi contrase&ntilde;a  <i class="glyphicon glyphicon-share-alt"></i></a>
        <a href="<?php echo $this->url('zfcuser/changeemail') ?>" style="margin: 4%"class="btn btn-primary col-md-2 "> Cambiar mi email  <i class="glyphicon glyphicon-share-alt"></i></a>
    <a href="<?php echo $this->url('zfcuser/register') ?>" style="margin: 4%"class="btn btn-success col-md-2 "> Crear Usuario  <i class="glyphicon glyphicon-plus"></i></a>

    <a href="<?php echo $this->url('zfcuser/logout') ?>" style="margin: 4%"class="btn btn-danger col-md-2 "> Cerrar Sesi&oacute;n  <i class=" glyphicon glyphicon-remove"></i></a>

</center>
<div style="clear: both"></div>
