<?php
$title = 'Modificar Lista de Municipios';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', 
    $this->url('municipio', array('action' => 'edit', 'id'=>$id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idMunicipio')) ;
echo $this->formRow($form->get('municipio'));
echo $this->formInput($form->get('submit'));
echo $this->form()->closeTag($form);

