<?php 
$title = 'Municipios';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('municipio', array( 
        'action'=>'add'));?>">Agregar Municipio</a></p>

<table class="table">
<tr>
    <th>Id Municipio</th>
    <th>Municipio</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($municipios as $listmunicipio) : ?>
<tr>
    <td><?php echo $this->escapeHtml($listmunicipio->idMunicipio);?></td>
    <td><?php echo $this->escapeHtml($listmunicipio->municipio);?></td>
    <td>
        <a href="<?php echo $this->url('municipio',
            array('action'=>'edit', 'id' =>$listmunicipio->idMunicipio));?>">Edit</a>
        <a href="<?php echo $this->url('municipio',
            array('action'=>'delete', 'id' =>$listmunicipio->idMunicipio));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
