<?php
$title = 'Modificar Datos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<hr>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('ciudadano', array('action' => 'edit', 'id' => $id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idConductor'));
?>
<div class="form-inline">
    <div class="form-group"> 
        <?php echo $this->formRow($form->get('nombre')); ?></div>
    <div class="form-group"> <?php echo $this->formRow($form->get('apellido')); ?></div>
    <div class="form-group"> <?php echo $this->formRow($form->get('cedula')); ?></div>
    <div class="form-group"> <?php echo $this->formRow($form->get('direccion')); ?></div>
    <div class="form-group"> <?php echo $this->formRow($form->get('telefono')); ?></div>
    <div class="form-group"> <?php echo $this->formRow($form->get('registroNro')); ?></div>
    <div class="form-group"> <?php echo $this->formRow($form->get('email')); ?></div>
    <div class="form-group" style="margin-top:1.5%"> <?php echo $this->formInput($form->get('submit')); ?></div></div>
<?php
echo $this->form()->closeTag($form);

